class Post {
  final String id;
  final String userId;
  final String? userFullname;
  final String content;
  final List<String> likes;

  DateTime? createdAt; //auto generated by supabase
  //final String? imageUrl; later...

  Post({
    required this.id,
    required this.userId,
    required this.userFullname,
    required this.content,
    // this.imageUrl, later
    this.likes = const [],
    required this.createdAt,
  });

  //fetching from db
  factory Post.fromMap(Map<String, dynamic> map) => Post(
    id: map['id'],
    userId: map['user_id'],
    content: map['content'],
    userFullname: map['full_name'],
    likes: List<String>.from(map['likes'] ?? []),
    createdAt: map['created_at'] != null
        ? DateTime.parse(map['created_at'])
        : null,
  );

  //sending to db
  Map<String, dynamic> toMap() => {
    'id': id,
    'user_id': userId,
    'content': content,
    'full_name': userFullname,
    'likes': likes,
  };
}
