class Post {
  final String id;
  final String userId;
  final String? userFullname;
  final String content;
  final List<String> likes;

  DateTime? createdAt; // auto-generated by Supabase

  // Frontend-only fields
  final bool isLiked;
  final int likeCount;

  Post({
    required this.id,
    required this.userId,
    required this.userFullname,
    required this.content,
    this.likes = const [],
    required this.createdAt,
    this.isLiked = false,
    this.likeCount = 0,
  });

  // Fetching from DB
  factory Post.fromMap(Map<String, dynamic> map) => Post(
    id: map['id'],
    userId: map['user_id'],
    content: map['content'],
    userFullname: map['full_name'],
    likes: List<String>.from(map['likes'] ?? []),
    createdAt: map['created_at'] != null
        ? DateTime.parse(map['created_at'])
        : null,
    // these default to false / 0, will be updated in StateNotifier
    isLiked: false,
    likeCount: (map['likes'] as List?)?.length ?? 0,
  );

  // Sending to DB
  Map<String, dynamic> toMap() => {
    'id': id,
    'user_id': userId,
    'content': content,
    'full_name': userFullname,
    'likes': likes,
  };

  Post copyWith({
    String? id,
    String? userId,
    String? userFullname,
    String? content,
    List<String>? likes,
    DateTime? createdAt,
    bool? isLiked,
    int? likeCount,
  }) {
    return Post(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      userFullname: userFullname ?? this.userFullname,
      content: content ?? this.content,
      likes: likes ?? this.likes,
      createdAt: createdAt ?? this.createdAt,
      isLiked: isLiked ?? this.isLiked,
      likeCount: likeCount ?? this.likeCount,
    );
  }
}
